
 //adding styling to the elements
  var body = document.getElementsByTagName("body");
  body.position = "relative";
  document.getElementById("body").style.padding = "0px 11vw";
  var paragraphs = document.querySelectorAll('p');
  
  // Adding the header

  var header = document.createElement("header");
  header.style.backgroundColor = "#FCE205";
  header.style.height = "100px";
  header.style.width = "100%";
  header.style.padding = "20px"
  document.getElementById("body").appendChild(header);
  var logoImage = document.createElement("img");
  logoImage.src = "https://rtbdemand.com/images/logo.png"
  logoImage.style.width = "10%";
  logoImage.style.height = "90%";
  logoImage.style.backgroundColor = "white";
  logoImage.style.borderRadius = "100%";
  header.appendChild(logoImage);

  

  
  // linking the css using javascript
  var head = document.getElementsByTagName('HEAD')[0]; 
  var link = document.createElement('link');
  link.rel = 'stylesheet'; 
  link.type = 'text/css';
  link.href = 'style.css'; 
  head.appendChild(link); 

  // attaching the logo image of RTB
  var headerDiv = document.createElement('div');
  headerDiv.style.display = 'flex';
  headerDiv.style.alignItems = 'center';
  headerDiv.style.justifyContent = 'center';
  var img = document.createElement('img');
  img.src = 'https://rtbdemand.com/images/logo.png';
  img.alt = "myImage";
  headerDiv.appendChild(img);
 
  document.body.appendChild(headerDiv);

  // creating random paragraphs using the js 
  for(var i=0; i<10; i++){
    var p = document.createElement('p');
    p.innerHTML = getRandomString(5);
    if(i === 1){
        var div = document.createElement('div');
        div.style.borderRadius = "5px"
        div.style.margin = "20px";
        div.style.padding = "25px";
        div.style.position = "relative";
        var button = document.createElement('button');
        button.id = "crossbutton";
        button.innerHTML = "x";
        button.style.color = "black";
        button.style.fontWeight = 400;
        button.style.border = "none"
        button.style.position = "absolute";
        button.style.bottom = "10px";
        button.style.right = "5%";
        button.style.backgroundColor = "white";
        button.style.width = "60px"
        
        button.style.cursor = "pointer";
        div.appendChild(button);
        
        var img = document.createElement('img');
            img.src = 'https://rtbdemand.com/images/rtbdemand-banner-A.jpg';
            img.alt = "myImage";
            img.style.height = "200px";
            img.style.width = "95%";
            img.style.borderRadius = "10px";
            img.id = "myImage";
            div.appendChild(img);
            document.body.appendChild(div);
    }
    function getRandomString(length) {
      var randomPara = "This random paragraph is generated by JavaScript.  ";
      for(var i = 0; i < length; i++) {
          randomPara += randomPara;
      }
      return randomPara;
    }
    document.body.appendChild(p);
    if( i == 9){
      var rtbEle =document.createElement("div");
      rtbEle.className = "earth";
      document.body.appendChild(rtbEle);
    }
  }

  document.getElementById("crossbutton").addEventListener("click", (event) => {
    document.getElementById("crossbutton").style.display = "none";
    document.getElementById("myImage").style.display = "none";   
  })

var paragraphs = document.getElementsByTagName("p");
  for(paragraph of paragraphs){
    paragraph.style.margin = '10px 0';
    paragraph.style.fontFamily = "'Courier New', Courier, monospace";
    paragraph.style.fontWeight = "500";
  }

  rtbEle.addEventListener("click", () =>{
    window.location.href = "api.html"
  });















 

