  //adding styling to the elements
  var rotateDeg = 20;
  var body = document.getElementsByTagName("body");
  body.position = "relative";
  document.getElementById("body").style.padding = "50px 200px";
  var paragraphs = document.querySelectorAll('p');

  
  // linking the css using javascript
  var head = document.getElementsByTagName('HEAD')[0]; 
  var link = document.createElement('link');
  link.rel = 'stylesheet'; 
  link.type = 'text/css';
  link.href = 'style.css'; 
  head.appendChild(link); 

  // attaching the logo image of RTB
  var headerDiv = document.createElement('div');
  headerDiv.style.display = 'flex';
  headerDiv.style.alignItems = 'center';
  headerDiv.style.justifyContent = 'center';
  var img = document.createElement('img');
  img.src = 'https://rtbdemand.com/images/logo.png';
  img.alt = "myImage";
  headerDiv.appendChild(img);
 
  document.body.appendChild(headerDiv);

  // creating random paragraphs using the js 
  for(var i=0; i<10; i++){
    var p = document.createElement('p');
    p.innerHTML = getRandomString(5);
    if(i === 1){
        var div = document.createElement('div');
        div.style.borderRadius = "5px"
        div.style.margin = "20px";
        div.style.padding = "25px";
        div.style.position = "relative";
        var button = document.createElement('button');
        button.id = "crossbutton";
        button.innerHTML = "X";
        button.style.position = "absolute";
        button.style.top = "2px";
        button.style.left = "2px";
        button.style.width = "60px"
        
        button.style.cursor = "pointer";
        div.appendChild(button);
        
        var img = document.createElement('img');
            img.src = 'https://rtbdemand.com/images/rtbdemand-banner-A.jpg';
            img.alt = "myImage";
            img.style.height = "200px";
            img.style.width = "95%";
            img.style.borderRadius = "10px";
            img.id = "myImage";
            div.appendChild(img);
            document.body.appendChild(div);
    }
    function getRandomString(length) {
      var randomPara = "This random paragraph is generated by JavaScript.  ";
      for(var i = 0; i < length; i++) {
          randomPara += randomPara;
      }
      return randomPara;
    }
    document.body.appendChild(p)
  }

  document.getElementById("crossbutton").addEventListener("click", (event) => {
    document.getElementById("crossbutton").style.display = "none";
    document.getElementById("myImage").style.display = "none";   
  })

var paragraphs = document.getElementsByTagName("p");
  for(paragraph of paragraphs){
    paragraph.style.margin = '20px';
  }


  var outSpan = document.createElement("span");
  outSpan.id = "mySpan"
  var myimg = document.createElement("img");
  myimg.id = "rotateImg";
  myimg.src = "https://yt3.ggpht.com/ytc/AKedOLTSqnub_4PzK8E6X7-9m8utThcY6YdsUqHw-nw=s900-c-k-c0x00ffffff-no-rj";
  myimg.style.height = "140px";
  myimg.style.width = "140px";
  myimg.style.borderRadius = "70px"
  button.style.cursor = "pointer";

  outSpan.appendChild(myimg);
  outSpan.style.position = "sticky";
  outSpan.style.bottom = 0;
  document.body.appendChild(outSpan);

  myimg.addEventListener("click", () =>{
    document.location.href = "api.html";
  })

  setInterval(() =>{
  if(rotateDeg === 360){
    rotateDeg = 0;
  }
  document.getElementById("rotateImg").style.transform = `rotate(${rotateDeg}deg)`;
  rotateDeg += 20;
},300)